lib/bill_web/router.ex
defmodule BillWeb.Router do
  use BillWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BillWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/opportunities", OpportunityController
    resources "/accounts", AccountController
    resources "/leads", LeadController
    resources "/contacts", ContactController
    post "/addnote/:id", AccountController, :addnote
    post "/addleadnote/:id", LeadController, :addnote
    post "/addcontactnote/:id", ContactController, :addnote
    post "/addopportunitynote/:id", OpportunityController, :addnote
  end

  # Other scopes may use custom stacks.
  # scope "/api", BillWeb do
  #   pipe_through :api
  # end
end

lib/bill/crm/contact.ex
defmodule Bill.CRM.Contact do
  use Ecto.Schema
  import Ecto.Changeset
  alias Bill.CRM.Account
  alias Bill.CRM.Note

  schema "contacts" do
    field :city, :string
    field :country, :string
    field :department, :string
    field :email, :string
    field :firstname, :string
    field :lastname, :string
    field :phone, :string
    field :street, :string
    field :title, :string
    belongs_to  :account, Account
    has_many :notes, Note

    timestamps()
  end

  @doc false
  def changeset(contact, attrs) do
    contact
    |> cast(attrs, [:firstname, :lastname, :email, :phone, :title, :department, :street, :city, :country])
    |> validate_required([:firstname, :lastname, :email, :phone, :title, :department, :street, :city, :country])
  end
end

lib/bill_web/controllers/contact_controller.ex
defmodule BillWeb.ContactController do
  use BillWeb, :controller

  alias Bill.CRM
  alias Bill.CRM.Contact

  def index(conn, _params) do
    contacts = CRM.list_contacts()
    render(conn, "index.html", contacts: contacts)
  end

  def new(conn, _params) do
    changeset = CRM.change_contact(%Contact{})
    country = CRM.get_countries
    account =  CRM.list_repo_accounts
    title = ["Mr", "Mrs", "Miss", "Dr.", "Prof."]
    render(conn, "new.html", changeset: changeset, account: account, country: country, title: title)
  end

  def create(conn, %{"contact" => contact_params}) do
    id = Map.get(contact_params, "account_id")
    account= CRM.get_account!(id)
    case CRM.create_account_contact(account, contact_params) do
      {:ok, contact} ->
        conn
        |> put_flash(:info, "Contact created successfully.")
        |> redirect(to: Routes.contact_path(conn, :show, contact))

      {:error, %Ecto.Changeset{} = changeset} ->
        country = CRM.get_countries
        account =  CRM.list_repo_accounts
        title = ["Mr", "Mrs", "Miss", "Dr.", "Prof."]
        render(conn, "new.html", changeset: changeset,  account: account, country: country, title: title)
    end
  end

  def show(conn, %{"id" => id}) do
    contact = CRM.get_contact!(id)
    changeset = CRM.build_contact_note(contact)
    render(conn, "show.html", contact: contact, changeset: changeset)
  end

  def edit(conn, %{"id" => id}) do
    contact = CRM.get_contact!(id)
    changeset = CRM.change_contact(contact)
    render(conn, "edit.html", contact: contact, changeset: changeset)
  end

  def update(conn, %{"id" => id, "contact" => contact_params}) do
    contact = CRM.get_contact!(id)

    case CRM.update_contact(contact, contact_params) do
      {:ok, contact} ->
        conn
        |> put_flash(:info, "Contact updated successfully.")
        |> redirect(to: Routes.contact_path(conn, :show, contact))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", contact: contact, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    contact = CRM.get_contact!(id)
    {:ok, _contact} = CRM.delete_contact(contact)

    conn
    |> put_flash(:info, "Contact deleted successfully.")
    |> redirect(to: Routes.contact_path(conn, :index))
  end


  def addnote(conn, %{"id" => id, "note" => note_params}) do
    #id = Map.get(note_params, "account_id")
    contact= CRM.get_contact!(id)
    case CRM.create_contact_note(contact, note_params) do
      {:ok, note} ->
        conn
        |> put_flash(:info, "Note created successfully.")
        |> redirect(to: Routes.contact_path(conn, :show, contact))

      {:error, %Ecto.Changeset{} = changeset} ->


        render(conn, "show.html", changeset: changeset, contact: contact)
    end
end
end

lib/bill_web/views/contact_view.ex
defmodule BillWeb.ContactView do
  use BillWeb, :view
end

lib/bill_web/templates/contact/edit.html.eex
<h1>Edit Contact</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.contact_path(@conn, :update, @contact)) %>

<span><%= link "Back", to: Routes.contact_path(@conn, :index) %></span>

lib/bill_web/templates/contact/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

<div class="columns">
   <div class="column col-6">
   <div class="form-group">
  <%= label f, :firstname, class: "form-label" %>
  <%= text_input f, :firstname , class: "form-input" %>
  <%= error_tag f, :firstname %>
  </div>
  </div>
 <div class="column col-6">
     <div class="form-group">
  <%= label f, :lastname, class: "form-label"  %>
  <%= text_input f, :lastname , class: "form-input" %>
  <%= error_tag f, :lastname %>
   </div>
  </div> 
  </div>


<div class="columns">
   <div class="column col-6">
   <div class="form-group">
  <%= label f, :email, class: "form-label" %>
  <%= text_input f, :email , class: "form-input"  %>
  <%= error_tag f, :email %>
</div>
  </div>

 <div class="column col-6">
   <div class="form-group">
  <%= label f, :phone, class: "form-label" %>
  <%= text_input f, :phone, class: "form-input"  %>
  <%= error_tag f, :phone %>
   </div>
  </div> 
  </div>

<div class="columns">
   <div class="column col-6">
   <div class="form-group">
   <label class="form-label">Account <a class="new_btn" href="/accounts/new">Create New</a></label>
     <%= select f, :account_id, @account, class: "form-select full_width" %>
  <%= error_tag f, :account_id %>
     </div>
     </div>
  </div> 



<div class="columns">
   <div class="column col-6">
   <div class="form-group">
  <%= label f, :title, class: "form-label" %>
 <%= select f, :title, @title, class: "form-select" %>
  <%= error_tag f, :title %>
  </div>
  </div>
 <div class="column col-6">
   <div class="form-group">
  <%= label f, :department, class: "form-label" %>
  <%= text_input f, :department, class: "form-input" %>
  <%= error_tag f, :department %>
   </div>
  </div> 
  </div>


<div class="columns">
   <div class="column col-12">
   <div class="form-group">
  <%= label f, :street, class: "form-label" %>
  <%= text_input f, :street, class: "form-input" %>
  <%= error_tag f, :street %>
   </div>
  </div>
    </div>
 

<div class="columns">
   <div class="column col-6">
   <div class="form-group">
  <%= label f, :city, class: "form-label" %>
  <%= text_input f, :city, class: "form-input" %>
  <%= error_tag f, :city %>
   </div>
  </div>

<div class="column col-6">
   <div class="form-group">
  <%= label f, :country , class: "form-label"%>
 <%= select f, :country, @country, class: "form-select" %>
  <%= error_tag f, :country %>
  </div>
  </div> 
  </div>

  
 
<div class="btn acc_btn3 float-right" ><a style="color:#b13231" href="/contacts"> Back </a></div>

       <%= submit "Create Contact", class: "btn acc_btn float-right white_text float-right" %>
       <div style="height:50px">  </div>
<% end %>

</div>
 </div>

lib/bill_web/templates/contact/form2.html.eex
<div class="new_note">
<%= form_for @changeset, @action, [class: "note-form form-inline", as: :note],  fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>
<div class="columns">
   <div class="column col-12">
   <div class="form-group">
   <%# <label class="form-label assign">Notes </label> %>
     <%= textarea f, :description, class: "form-input" %>
  <%= error_tag f, :description %>
     </div>
</div>
</div>

<div> <%= submit "Add", class: "btn acc_btn_4  white_text" %></div>
<% end %>
</div>

lib/bill_web/templates/contact/index.html.eex
<a class="btn acc_btn float-right"  style="color:white" href="/contacts/new" > Create Contact </a>

<div class="account_page_div">

<table class="table">
  <thead>
    <tr>
  
      <th class="fullname">Full Name</th>
      <th class="email">Email</th>
      <th class="phone">Phone</th>
      
      <th class="account">Account(s)</th>



    </tr>
  </thead>
  <tbody>
<%= for contact <- @contacts do %>
    <tr>
<td class="mar"><%= link contact.firstname, to: Routes.contact_path(@conn, :show, contact), style: "color: #363636; font-weight:550"%><span> </span><%= contact.lastname %></td>

      <td><%= contact.email %></td>
      <td><%= contact.phone %></td>
     <td><%= contact.account.name %></td>
    

    </tr>
<% end %>
  </tbody>
</table>

lib/bill_web/templates/contact/new.html.eex
<a style="color:black" class="btn acc_btn2" href="/contacts"><b> < </b>Back </a>

<div class="new_account_page_div">
<%= render "form.html", Map.put(assigns, :action, Routes.contact_path(@conn, :create)) %>

lib/bill_web/templates/contact/show.html.eex
<a style="color:black" class="btn acc_btn2" href="/contacts"><b> < </b>Back </a>

<div class="show_lead_page_div">

<div class="lead_text">Personal Details</div>
<div class ="summary ">
<div class ="lead_content">
  <div class ="lead_name"><%= @contact.firstname %> <%= @contact.lastname %> </div>

<div class ="lead_field"> <i class ="fas fa-envelope icon"></i> <%= @contact.email %>  </div>
<div class ="lead_field"> <i class="fa fa-phone icon"></i><%= @contact.phone %>  </div>
<div class ="lead_field"> <i class="fas fa-user icon"></i><%= @contact.department %>  </div>
<div class ="lead_field space"> <i class="fas fa-address-book icon"></i><%= @contact.street %>  </div>


</div>
</div>
</div>
<div class="show_lead_page_div2">
<div class="lead_text">Accounts</div>
<div class ="summary ">
<div class ="lead_content">
   <%= link @contact.account.name, to: Routes.account_path(@conn, :show, @contact.account), class: "btn btn-link show-link", style: "color:#4a90e2" %>
</div>
</div>
</div>
</div>

<div class="show_notes">
<div class="columns note_title"><div class="column col-9"><p class="clear"><b>Notes</b></p></div><div class="column col-3"><a id="b1"  class="plus">New Note</a></div></div>
<div id="hidden" >
<%= render "form2.html", Map.put(assigns, :action, Routes.contact_path(@conn, :addnote, @contact)) %>
</div>
<%= for acc <- @contact.notes do %>
<div class="note_view">

<%= acc.description %>
<div class="time"><%= acc.inserted_at %></div>

<% end %>

</div>